[project]
name = "mi-proyecto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VirtualZen", email = "44878852+VirtualZen@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
]

[project.scripts]
mi-proyecto = "mi_proyecto.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
