[project]
name = "lab03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paul Gomez Ehmig", email = "apgomez@estud.usfq.edu.ec" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "nbconvert>=7.17.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.21.0",
    "ucimlrepo>=0.0.7",
]

[project.scripts]
lab03 = "lab03:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
