[project]
name = "duckdb-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VSCode User", email = "user@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.5",
]

[project.scripts]
pato = "pato:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pato"
